service: crawler-sls
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  timeout: 30
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          cors: true
          method: get
